### ISSUE TITLE
Need to remove the -- in front of the keep linker option otherwise will fail

### ISSUE THREAD

**Issue by xandark** [jeremysrand/Apple2GSBuildPipeline#1]
I'm finally using this awesome build pipeline with the latest Golden Gate and bringing in my old sources from 1995. I have a project with 92 source files and I needed a sane way to handle building it.

I'm using this on KDE neon Linux. I don't have a Mac for Xcode. This is the first issue I found...

In tail.mk at line 128, there's an issue that was preventing the linker from finishing: 

`	cd $(OBJDIR); $(LINK) $(LDFLAGS) $(patsubst $(OBJDIR)/%, %, $(BUILD_OBJS_NOSUFFIX)) --keep=$(TARGETDIR)/$(PGM)
`

this needs to be changed to:

`	cd $(OBJDIR); $(LINK) $(LDFLAGS) $(patsubst $(OBJDIR)/%, %, $(BUILD_OBJS_NOSUFFIX)) keep=$(TARGETDIR)/$(PGM)
`

and similarly on line 157:

`	cd $(OBJDIR); $(LINK) $(LDFLAGS) $(patsubst $(OBJDIR)/%, %, $(BUILD_OBJS_NOSUFFIX)) --keep=$(BINTARGET)
`

change to:

`	cd $(OBJDIR); $(LINK) $(LDFLAGS) $(patsubst $(OBJDIR)/%, %, $(BUILD_OBJS_NOSUFFIX)) keep=$(BINTARGET)
`

In both cases, the change is subtle. I need to remove the -- from before the keyword keep. If I don't, then I get this with the "iix --trace-gsos link":

GetFileInfoGS(--keep=./Animasia.3D)
GetFileInfoGS(--keep=./Animasia.3D.a)
GetFileInfoGS(--keep=./Animasia.3D.A)
GetFileInfoGS(--keep=./Animasia.3D.root)
GetFileInfoGS(--keep=./Animasia.3D.ROOT)
Terminal error: Could not open file --keep=.:Animasia.3D.ROOT

It thinks that "--keep=./" is part of the filename. When I do a "iix help link", the option is specified like this:

`KEEP=      Saves the finished program to outfile.
`

**Comment by jeremysrand** [comment]
It is interesting that this didn't fail for me on MacOS.  I have done some testing and it looks like everything works as expected without the -- characters before keep so I have pushed a fix for this in tail.mk.  I believe this should address the issue you were seeing.  Thanks for the bug report!
