### ISSUE TITLE
Non Xcode platforms spew out several lines of errors

### ISSUE THREAD

**Issue by xandark** [jeremysrand/Apple2GSBuildPipeline#2]
This is the second issue I found...

In tail.mk at line 99 under the xcodefix stanza, I have to comment it out like so:

```
xcodefix:
#	defaults write "$(ORCAM_PLUGIN_INFO)" $(XCODE_PLUGIN_COMPATIBILITY)s -array `defaults read "$(XCODE_INFO)" $(XCODE_PLUGIN_COMPATIBILITY)` || true
```

otherwise I'll get a lot of messy, hard to understand errors at the top of my make build:

```
defaults write "/home/michael/Library/Developer/Xcode/Plug-ins/OrcaM.ideplugin/Contents/Info.plist" DVTPlugInCompatibilityUUIDs -array `defaults read "/Applications/Xcode.app/Contents/Info.plist" DVTPlugInCompatibilityUUID` || true
defaults read: couldn't read default
2020-11-21 18:58:59.173 defaults[8822:8822] File NSData.m: 1823. In -[NSData writeToFile:options:error:] mkstemp (/home/michael/GNUstep/Defaults/home/michael/Library/Developer/Xcode/Plug-ins/OrcaM.ideplugin/Contents/Info.plist.plistQBVIGf) failed - No such file or directory
2020-11-21 18:58:59.173 defaults[8822:8822] Failed to write defaults database to file: /home/michael/GNUstep/Defaults/home/michael/Library/Developer/Xcode/Plug-ins/OrcaM.ideplugin/Contents/Info.plist.plist
```

Is there some way to add an environmental sensing aspect to this pipeline so that if you're not running Xcode, you don't see these errors?

I'm using this on KDE neon Linux. I don't have a Mac for Xcode.

**Comment by jeremysrand** [comment]
I just pushed a fix for this which I believe should work.  I am making the line conditional on uname returning Darwin which is what I get under MacOS.  As long as your OS returns something other than Darwin from uname (which I would assume all non-MacOS systems would), I think it should guarantee that this command is not executed.

But, as you can tell, I have done no testing of these makefiles and build scripts on a non-MacOS platform.  So, if you can verify that this change solves the problem for you, that would be great.  Thanks!

**Comment by xandark** [comment]
Okay, with your change this is what I'm getting at the top of my build:

```
[ `uname` == Darwin ] && defaults write "/home/michael/Library/Developer/Xcode/Plug-ins/OrcaM.ideplugin/Contents/Info.plist" DVTPlugInCompatibilityUUIDs -array `defaults read "/Applications/Xcode.app/Contents/Info.plist" DVTPlugInCompatibilityUUID` || true
/bin/sh: 1: [: Linux: unexpected operator
```

So it's thinking that the output of uname is an operator.

Maybe it's working for you because Make is using a subshell different than /bin/sh? Because if I change the relevant line in tail.mk to:

```
[ "`uname`" = Darwin ] && defaults write "$(ORCAM_PLUGIN_INFO)" $(XCODE_PLUGIN_COMPATIBILITY)s -array `defaults read "$(XCODE_INFO)" $(XCODE_PLUGIN_COMPATIBILITY)` || true
```

...then it works. The fix is using a single = instead of a double == in the uname comparison, which is what sh uses for testing string equivalency. 

I just tested using a single = using Bash, and it works that way. So could you test with a single = on your Xcode build system for me?

**Comment by jeremysrand** [comment]
Yes, I should have used a simple = for the test.  The man test page on MacOS also says the operator is a single equals sign and makes no mention of == at all.  But apparently that works and I have been doing too much C coding recently to notice my mistake.  It should have been single equal sign.

I have confirmed that this still works as expected with a single = under MacOS and it should eliminate the problem you were seeing.  Sorry for needing the second kick at the can here.

**Comment by xandark** [comment]
Great, works for me now.
