### ISSUE TITLE
Update Unix installation

### ISSUE THREAD

**Issue by xandark** [jeremysrand/Apple2GSBuildPipeline#4]
In the readme.md under UNIX Installation, it says

> That said, I haven't tested this on any other platform to show this is actually true.

I think it can be safely changed to read that it has been tested and that it works.

**Comment by jeremysrand** [comment]
Thank you for all your help finding these issues.  I have updated the readme and specifically gave you credit for your work here.  Thanks so much!

**Comment by xandark** [comment]
Glad to help :)
