### ISSUE TITLE
createDiskImage needs cp to preserve xattr's under Linux

### ISSUE THREAD

**Issue by xandark** [jeremysrand/Apple2GSBuildPipeline#5]
The filetype/auxcode aren't set in the resulting .img file even though it appears to be set when I do a iix ls -l

The fix is in make/createDiskImage file, line 62. If I change from:

`cp "$FILE" "$DEST"
`

to:

`cp --preserve=xattr "$FILE" "$DEST"
`

... I get the proper filetype/aux for my s16 inside the newly created .img file.

**Comment by jeremysrand** [comment]
I changed createdDiskImage so it should pass those arguments to cp now on non-MacOS systems.  It isn't the most general solution and I have a comment in there saying as much but I think it is sufficient for now.  I believe it should work for you.

**Comment by xandark** [comment]
Looks good. I did a make clean and a new make and everything works good on this end.
