### ISSUE TITLE
Incorrect settings for Merlin templates

### ISSUE THREAD

**Issue by roughana** [jeremysrand/Apple2GSBuildPipeline#7]
Merlin [CDA filename](https://github.com/jeremysrand/Apple2GSBuildPipeline/blob/b108be5698750f27d8bc40dc15926550c11029ed/pkg/Templates/Apple%20IIgs/Merlin%20Classic%20Desk%20Accessory.xctemplate/linkscript.s#L17) should end with .CDA instead of .S16<B>
Merlin [Control Panel filetype](https://github.com/jeremysrand/Apple2GSBuildPipeline/blob/b108be5698750f27d8bc40dc15926550c11029ed/pkg/Templates/Apple%20IIgs/Merlin%20Control%20Panel.xctemplate/linkscript.s#L10) should be $BC<B>
Merlin [Control Panel filename](https://github.com/jeremysrand/Apple2GSBuildPipeline/blob/b108be5698750f27d8bc40dc15926550c11029ed/pkg/Templates/Apple%20IIgs/Merlin%20Control%20Panel.xctemplate/linkscript.s#L17) should end with .CDEV instead of .S16<B>
Merlin [NDA filetype](https://github.com/jeremysrand/Apple2GSBuildPipeline/blob/b108be5698750f27d8bc40dc15926550c11029ed/pkg/Templates/Apple%20IIgs/Merlin%20New%20Desk%20Accessory.xctemplate/linkscript.s#L10) should be $B8
Merlin [NDA filename](https://github.com/jeremysrand/Apple2GSBuildPipeline/blob/b108be5698750f27d8bc40dc15926550c11029ed/pkg/Templates/Apple%20IIgs/Merlin%20New%20Desk%20Accessory.xctemplate/linkscript.s#L17) should end with .NDA instead of .S16

**Comment by jeremysrand** [comment]
Thanks for pointing out these errors in the link scripts.  I have fixed them in the latest commit.
