### ISSUE TITLE
Inconsistent whitespace usage within files

### ISSUE THREAD

**Issue by roughana** [jeremysrand/Apple2GSBuildPipeline#9]
Differences in whitespace style between tabs and spaces display awkwardly in different editors, so ideally consistent style is used everywhere, but especially within each file and particularly with nearby lines. 
I picked up on these specific instances that are inconsistent with the immediate surrounding lines:
https://github.com/jeremysrand/Apple2GSBuildPipeline/blob/b108be5698750f27d8bc40dc15926550c11029ed/pkg/Templates/Apple%20IIgs/ORCAM%20Classic%20Desk%20Accessory.xctemplate/TemplateInfo.plist#L14
https://github.com/jeremysrand/Apple2GSBuildPipeline/blob/b108be5698750f27d8bc40dc15926550c11029ed/pkg/Templates/Apple%20IIgs/ORCAM%20Classic%20Desk%20Accessory.xctemplate/TemplateInfo.plist#L140
https://github.com/jeremysrand/Apple2GSBuildPipeline/blob/b108be5698750f27d8bc40dc15926550c11029ed/pkg/Templates/Apple%20IIgs/ORCAM%20Classic%20Desk%20Accessory.xctemplate/TemplateInfo.plist#L201

**Comment by jeremysrand** [comment]
This happened because I started with template.plist files with tab indentation and then modified it using an editor set to expand tabs to spaces.  I have standardized all of the template.plist files to use tabs for indentation.

**Comment by jeremysrand** [comment]
This is resolved with the latest commit.
